view_queue_route:
    path: /viewqueue.php
    defaults: { _controller: mafiascum.signup.viewQueue:handle }
view_game_route:
    path: /viewgame.php
    defaults: { _controller: mafiascum.signup.viewGame:handle }